{% set name = "kled" %}
{% set version = "1.2.9H11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CoREse/kled/releases/download/v1.2.9H11/kledv1.2.9H11.allmodules.tar.gz
  sha256: b0f74b7ca1a4458873907d75dce0b2079b0af1fb26facdf15dde337cb4e2c4fb

build:
  number: 0
  skip: True  # [osx]
  run_exports:
  - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - make
    - automake >=1.16
    - autoconf >=2.69
    - autotools_clang_conda  # [osx]
    - llvm-openmp  # [osx]
  host:
    - zlib >=1.3
    - bzip2 >=1.0
    - liblzma-devel >=5.8
    - libcurl >=8.0
    - openssl >=3.5
    - libdeflate >=1.24
    - libboost-devel >=1.84
    - gmp
    - openmp  # [linux]
  run:
    - zlib >=1.3
    - bzip2 >=1.0
    - liblzma-devel >=5.8
    - libcurl >=8.0
    - openssl >=3.5
    - libdeflate >=1.24
    - libboost-devel >=1.84
    - gmp
    - openmp  # [linux]

test:
  commands:
    - kled --help
    - kled --version

about:
  home: https://github.com/CoREse/kled
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An ultra-fast and sensitive structural variant detection tool for long-read sequencing data
  description: |
    Kled is designed to call SVs nicely and quickly using long-read sequencing data. 
    It takes mapped reads file (bam) as input and reports SVs to the stdout in the 
    VCF file format. Kled can yield precise and comprehensive SV detection results 
    within minutes and can run on any modern computer without needing of any field 
    knowledge of the user to perform the SV detection.
  doc_url: https://github.com/CoREse/kled/blob/master/README.md
  dev_url: https://github.com/CoREse/kled

extra:
  recipe-maintainers:
    - CoREse
  identifiers:
    - biotools:kled
    - doi:10.1093/bib/bbae049
    - doi:10.3389/fgene.2024.1435087
